### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by gr4kk3r** [flufficat/yt-boat#24]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**
A clear and concise description of what you want to happen and when.

**Additional context**

**Comment by flufficat** [comment]
Hi @gr4kk3r What kind of request is this, thank you.

**Comment by gr4kk3r** [comment]
Sorry, not really a request, just letting you know that you have
your home directory hardcoded into the yt-boat script.

-Lang


On 23/07/12 06:14AM, flufficat wrote:
> Hi @gr4kk3r What kind of request is this, thank you.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/flufficat/yt-boat/issues/24#issuecomment-1632509849
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
I just read a book about Stockholm syndrome. It was pretty bad at first, but by the end I liked it.

**Comment by flufficat** [comment]
new release should be out soon. Thanks
